# Generated by Django 4.2 on 2024-08-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_cover',
        ),
        migrations.AddField(
            model_name='album',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='album_images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images'),
        ),
    ]
