# Generated by Django 4.2 on 2024-08-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_remove_album_album_cover_album_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(upload_to='album_images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(upload_to='artist_images'),
        ),
    ]
