# Generated by Django 4.2 on 2024-08-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0003_alter_album_picture_alter_artist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(default='default_album_image.jpg', upload_to='album_images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images'),
        ),
    ]
